name: "Rodrigo"
description: "The Personal Homepage for Rodrigo Méndez Rojano"

url: "http://rodrigoMendez_notfound.com"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
